---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-config
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgAGmG1/tl+RZpsYUFu70MLkFyWzWCuZjuQ8hJNSu6usD1oBQ/lk8a7L8wPzNrQPDjLJ4Z13kn6nprxq5ZM9sZdLgtIZoDYeXtm5cKYw20z/V9Bzh8bke4PobDaTO452/MJVyYZzC4tJyR303YUqeCZCgrhyHnAVq67DnCaA19NQyjmbbZLZnn8fhXAqvCA1CnAUPs8uToiNwRXHYjX6osi9x+qJLMYhz35+0Icqxu8qfRhIk2VBzuA0vAayvsOiqj9K19RWyrgHGP/+ljDGT4VA1ubM1uJ77R5MAU1qIJ9T5RiQVvv4MzeccQYYJ/TmR9X/Ks5LNlanLLjVM6amFX+Pw4tk0lhmU+drvxMrJ4FcfYUgCZIymf914rj4OIP/aV5R1daItKVPPMyO8zhI6z9/2bw1ZJiheQXhPeDXu+s+4L2hMmaCXBGNUXpPgOpUWMXihqsMvVileSbIEN1GJuyd0dmVCaB9ALX1Bb7BQuSZ/Bax4Ak6tl9oSbnMojLLGKmQVuQf0vlfheklHxC88cQTjZs+ilsh4XN4ljMIvGztvRfo1qLG/eiRWXc2s0O6HiyP5ULiAiI/bPin2S+3b50aYdOdijmwxbYi74CrEUNQISB9whF39m6TH0Ak9ShIzgxWj49dlEGfRmiUyzn+o3SC8zBfVCNVs/6ohAsZ1Ggmp+jgJUx4XjoZspNqKxG2soOgjR0lrJ7doq3v+3PLzifwuxmCByfp8LdyuBenh+EbA4WoR0nPY4tCVStlfxTAB7kdPnI8hb6IFj0I0Lvwky2Z
  template:
    metadata:
      name: authentik-config
      namespace: authentik
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  encryptedData:
    postgres-password: AgB9VfKDP68nPLznw3PplKCdsqFNtLSH08rvNjWqMdrzL6a9izlhzOXI/09een50aS6sDuh7VTcHVKWgymkHzNlEgzqRbttZBinV6ixcPuXYvHeyIlYDiaZM4INU08MrmBlWi4OBhylCctpU9nc7ki8DJuzK1NJpUdqVj3FuSwd5IBwOuXIAth4UXcPRqVkagEybnOY+wsyYKv6IdbsLP6fQQWLqjUXkQiqKgN76rDHmYnmDBfAD3Rvyo/a5Cnb+Xebt98EkbrSwuG0YoYaj1DAQNJrCk/as9/7vA8vpCToMuGv5uLJphWj3f4HfI8xl07WcrQX6s4MGE3mzhDCWDbz1RhDJgEqXhD0dnp1/1l10i+jhWT5SCuEVCFBlqfOBltIHLVdTWLPAiEhVRcptYwq6zM8jsDQG9qGc2f/Lrnw/1QNNXgmtTVZnjsDRRfv4YjgCdyC0ny/BZoeGqzyRNGmTm6sj1t6krxLM4KLeQZUan0xs1tv7sz5TrTW8/Fk6D1sn7ky1Q8gogvubx2GxCcgiHKow11VJvQFY4v4eMEAcwppQxiLAhD2//u51uqZ4fY6Ht3HkBHwuNf//HKaMxlC7/VfLqUpU2FuPx5UOVdveBR7WFbsmIeDk2VOvk2sSjpkYKYoF9q4rk/kE7A7HcLKi6zPLTjssDf1TLDu3p4JOoBsd3B3uSrm1bU/cwNhEFKkiL6XHN9o3wcSa7BQfNVqcxIjOZJbd8KkWzOGzxpkHIwjsmx5hEqfJvZN+8g==
    password: AgAGXrTyxD/age1fAh0aYNChOWH5P/SPX8MKyfg/HbR4kdhsBEQFknolgcl69Aozd8TKHunQBMeW8ZOabeCxjIF7phf8xsPn2qhFctBxIatSb7NflGxVUbzNusnra9CQwjtBzaeqYQZUXU3pPtRRHHGwP3Pez2Ua2EsNR4j6ziAVNp96BSJS0m7PG8Qx2NJlrxeSADQubV9Q4qgZC2BSoARDkJXh7z0G78W0VcveOBms3HIamdqH5IpPru/Be43/Hl6kDusv236ITOeIw+I+9ri7AACLgSnWZbfxebJ72rO0ro++39q1rVTAd4oU4f9HPPRTsnhRCNGm5+9ujItwpS8e2wtMohHXSU7VMw7Ev2bj2z3950fDwOOAUgwGoVtPQeUJAV8EYN2EpVl6ueteaKAC+IwJQRIK/xcVeLJyVJvzzjPvj0IAs9mV3QiLCzY0gPa5X7zL4n5C77z7uDfpj/eE6ZMSqhXz+aj3zkjdAFT9QIVZTRnfmhXuwdhy8XNFJb2QewihgPz5mQxWjBLTcQER7jk0C+JyL6vzySxaCKgAIS19Qzr7Ad2J4BgKPl4051I2Pz/cWQUGWbtHnmhy7ILMDtweSCfWbq2NIsHETayoNXOfS3c9lZJztXnlzyiIw2zWznw3ba9R5jnJsKlU1hTbiOTwPZ5f7NuQFg+BYuBYDUdY3cU+xlmYxQLrJ2CQUe4nlGKD7yZlkjEI76wxQQ/g2/IZzIlsBRMNWXcEg6h6P8lVC5Unxtc+WzZR0A==
  template:
    metadata:
      name: authentik-postgresql
      namespace: authentik
