---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-config
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgAGmG1/tl+RZpsYUFu70MLkFyWzWCuZjuQ8hJNSu6usD1oBQ/lk8a7L8wPzNrQPDjLJ4Z13kn6nprxq5ZM9sZdLgtIZoDYeXtm5cKYw20z/V9Bzh8bke4PobDaTO452/MJVyYZzC4tJyR303YUqeCZCgrhyHnAVq67DnCaA19NQyjmbbZLZnn8fhXAqvCA1CnAUPs8uToiNwRXHYjX6osi9x+qJLMYhz35+0Icqxu8qfRhIk2VBzuA0vAayvsOiqj9K19RWyrgHGP/+ljDGT4VA1ubM1uJ77R5MAU1qIJ9T5RiQVvv4MzeccQYYJ/TmR9X/Ks5LNlanLLjVM6amFX+Pw4tk0lhmU+drvxMrJ4FcfYUgCZIymf914rj4OIP/aV5R1daItKVPPMyO8zhI6z9/2bw1ZJiheQXhPeDXu+s+4L2hMmaCXBGNUXpPgOpUWMXihqsMvVileSbIEN1GJuyd0dmVCaB9ALX1Bb7BQuSZ/Bax4Ak6tl9oSbnMojLLGKmQVuQf0vlfheklHxC88cQTjZs+ilsh4XN4ljMIvGztvRfo1qLG/eiRWXc2s0O6HiyP5ULiAiI/bPin2S+3b50aYdOdijmwxbYi74CrEUNQISB9whF39m6TH0Ak9ShIzgxWj49dlEGfRmiUyzn+o3SC8zBfVCNVs/6ohAsZ1Ggmp+jgJUx4XjoZspNqKxG2soOgjR0lrJ7doq3v+3PLzifwuxmCByfp8LdyuBenh+EbA4WoR0nPY4tCVStlfxTAB7kdPnI8hb6IFj0I0Lvwky2Z
  template:
    metadata:
      name: authentik-config
      namespace: authentik
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  encryptedData:
    password: AgDRZ4RgxXnPbF6JvCFCoLXBmN3gyQmzQKy8kqH7RMHtR2oqd1J+QiQyR3C6YvCkWPX6xyBxPmSHCX0OCp9DpDW+rPUoszetVnUDJhLkHqpmyxUgFDvzQFoSAkW5re3hfgkMyRtcaiVKA1+Ask8SjisceusMqCOXZFO6aWZaAlpX8+GcPgQiF9gDloyP7gmYN02EKO1Qub2KhanpBtGwSsn5Z9ptERizuXZDd2hXi7ZrjoMfTBAsHjLCDNRt04ipQxmwK3YLVmveeJ4sPaCwkZ2g9oDwI4u//ySNil1Ih7gu9/q/W/9W8GaYEeuK9B1/9gbpHQQWNU5yTAWVTtgRVfTss+4r6T7WNscKTLKoecnj2iAuTWDsMQh35w3rG+oXoWgdo21yDo5gtCRhbKqcwyuL/hzPcNO3eQ98gzGjJRtICLb9WkTj5QoBUNvj7Uv/V3KweHR/1oBYnHYrO+DUbQqnjp/F/UcqG9xLdIGQAVtE7zgW7fS1yVz1Tb7kQUx+P+mdRJyb4GXPbhd7iJDsDKj4BQ8DCK+qwqH/nSSDNI0xnH+qb0Fdo5v19dIb1LCVl/obvcff/nmsovhLD16JOohpl59HnqPaliQGQouP0lyBAqFRChAoRdCzUwYgMWOODt+M7Uh/CVSm2KO6uZ1UaEacMl+wmDsmC5AIRDoZzHKvDww5q1wA54B0PkRvWJTMphf8ZRtD99Kv39EgmT1oxpDSiUlpMljevsGfmNfMIAdSJAPfjLSLeEnwsOZ6Lg==
    postgres-password: AgCycPrfxwrLAF4GE4cZb/hkiu6kCrXlUKDogwz09TYMePmpKDWut226OjUSVyyZT+VKQiEk3aWlysxjVybnMMAEyjO9m+AlfVONClzT9pWJTNceZDRq0tpVz2/avRKX1i1iAr8KtuTLMXylEdgq4RfsTTiLfIFHc9I+NvsWXX8jhuGM+wUPL7/QhbLnw6mFMdkyh+E6oqYAOJh45dmRZGn7S2pxnEZ+yrnMOsswnBSZCC+3k2w207rsS/nk91gFKGul+5+qKjUTlBmTdg6MTxwV5VI8vzgKD7zWhpUWP1hlJnWPh6e4i0waJzX1ZnwGZyXDcqPnqMIGx+svNKZ6UMnWrPC4WiFtf5OnDV8haNYlBznpZ2s0uPpc5elP8+KTLyv1Bhtr/uYnQks0boGQRqwSE6PDhV9S9QzefA3vJqWszKGLkPSVAzfb45tIj4EwGL04tpU8qqm5RnC6DRKZIIjUUvy3jfJIy7AysQMY78RbgPps0WxO1TBRxPvFbbGc0qFRh6aqDdij+MqqkaTqNWn6zSFA+lEMYlX4Ckk1w/TJiAcMl8z+jrHEOEnGzlQiPLc8rCI9iy0b0bindTrBP7tAaCqwvQRa5zqTSdgpxC8dVu0nnSIzdoNnxd1x7FsSJNYBE9b3KAcpBt4MvFy1CZKoiQ786oq7DHLQDJS5b2oO6ZxZU2p6ZqCfO8hm7MaJa+02PXiKqWfT89wp3TOQHjQtbGilCuh0LegSfwwpBS32gV0IL41YYYaokjRK9A==
  template:
    metadata:
      name: authentik-postgresql
      namespace: authentik
