apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: date-app
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: date-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: date-app
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: date-app
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: date-app
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: date-app
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
