apiVersion: v1
kind: ConfigMap
metadata:
  name: home-arpa-ca
  namespace: monitoring
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFLDCCAxSgAwIBAgIUF111WOlVP1qVNrxI4jnJuhx5yAYwDQYJKoZIhvcNAQEN
    BQAwLjEQMA4GA1UEChMHaG9tZWxhYjEaMBgGA1UEAxMRaG9tZS5hcnBhIFJvb3Qg
    Q0EwHhcNMjYwNTAzMDQ0OTI0WhcNMzYwNDMwMDQ0OTI0WjAuMRAwDgYDVQQKEwdo
    b21lbGFiMRowGAYDVQQDExFob21lLmFycGEgUm9vdCBDQTCCAiIwDQYJKoZIhvcN
    AQEBBQADggIPADCCAgoCggIBALw/yRphgqa8Vqe1+X9YcYUP1it141cDvTYneBJa
    mudsP3As0mn+2WJSnccpl9Myge8SElKpShyhNk0Bb8AGykQnb6sSWivFeY6YFZ6U
    QrL8869x8IBI3oENsyl8dPALJlmgOdJcQX7KGevxXlVTTiXz0YUojE7CQOck+YF9
    vImbhZvWN7OM08PI6oOfYzVHt/O2n9m5BU2750iGQhejb291fLzWhBMB+p++rtzu
    so7El9zNHIlSTQRH+POxtCzHqUXAN8Mg6S7NrxBCHLRE4Ee7LDIhK+nMxVqLV8mN
    /Y05Hm15OaYo4bLW206UtddwoAmOScNIoDPKSVN8aY6jsaiPKQ221wQRL2ykylvp
    kM9DorwwAfFcLPXOyVnKrS05elhKS5fqI7Xtx97T43XIdF1rN7L4DI1I7wtYXZB3
    jGpWtlvADWTl7EmW35Zhb/ATm26avsJjrpdc3WmXBieLJYbKOSjeztCeZdwOD879
    Vrn+789yIBYG8snCvUYY+6vvFD+AC2EcXYxaYiOC5DCzWDyWmBClS+LDSFNGi+DK
    vhQV1mHZVlf4Vy5FuJp3z8JfcWci9Q3z5EQKRQR1mhzj7jnuSvBKmHYFcpuoQZzP
    eMsH42ysosZl1QjtNgN9zERTAFEKyGpeoQl+UV9eYkUnyfcauECjonR8TcbpTVjF
    uY6fAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0G
    A1UdDgQWBBSbxZG3PVsvWzQTJXWLQJPr6SjdZDANBgkqhkiG9w0BAQ0FAAOCAgEA
    aVzYulG9BIQuW8JNp9kCI9naflH9ak2pWE93iUc1IabFvDVJuaNRD5WiGpHVWNWR
    cxUXu0KhhFP5UnzpjHYIcIr1kYDDopBDR7HdkbXMXAulaGKD0PDg0Me0gORYCsVn
    xxG8hiWKyt3Mm3sFnD9SAeqCHpkCwMgpSHSJRRpw1gQjMPBP3PJB0JBy9i4a82sz
    b+ki235ZYca0EEDzZ1j/1bnLwKwS9EihksJPzgfJQrQIUgqaoIPJHuKhf3fhyepa
    IJ4JpdOOkpP7KKfWiBX7iTLYeF0yHCQa/hvfYlXIZIHPJ+Obj4Zv87epeGZZJ3c8
    eMIc2DUba19wVQdNixfM4YPo2jXBv5E2je4j34Ea4OcnpIX6+nAbgQBqMcuVDaDj
    YZM8tYArfsqVAMLjSHtv6e0bZOGeL/QqkurOQTrtr2Qpll2/y7y+e9W4Npl72P6V
    EsRfFvBr2hKwR/rfKbGLLmzFBKG8qmsr5fsRHD0jsy7IFNC5ki0wB9Kti8LmQud5
    Cn72/f1zgR2Jv/k1fcY4bc4Aq2dERTJzTfdpb7heJ/zK2rWkUvlzMDbxsv5i+oxM
    1Zn16jwHCZpLgn30oNcK4vYuv+LcxJnWSVlZEa/38Id0iI4VBsUFCAzjzXZbj6N0
    c6TDRE0+LAa8eQ74ESURZn3zQfiR4N8e+mugbTglGIs=
    -----END CERTIFICATE-----
