apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-bot-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgA27OVkNJO78eCu01Jg2cJoo8H8sQ9ClOrb7nm3pZOLZB5RnLHRPoIbwcoYG/OmDUhuc7vp/3FvPyDXqeCNpXj/5sv9GHWc8wIghNGac1jbD5hljcCPx4unfXO5pnseD33MU9STc8bFH1gSsU12EW2l6FkTtXWwPDydU0rRuExaOhsgeMGIc/7giAKufNVxD5CCR0yq07MQCpM3XIAH4A46BnBqDYWBfNYSWzd44w6Znhras5oeDZtZKNVCZdjaJ35yMxWrbLatxZabWJBM77EpxMz3BMOEiQfE+WLhegjwtv0txfyY4BVy/B48cObL4yWi7B7SNxKegEiiUuK8uopSHvCcXVeGr0dyKj5i8fQgHh39cMXBarh6krq88r0ucMYFYQAbSu4JYICAhefuVvvEXq8kkFJElwr3hsfNNf3t4t9pm1meCk2pXdULtRuquOVslZQc8FxmBBOmLp7kf0akNHCRAhyZQ61c+RLfKIDuqOUOm54CvOk7XoCBB/3gPkUVXOfkfk0SUwmTaTUsYN43f/Df+EPT/l7/BV9QTZh2PPPudfGvyMwZXB+yHKq+L30VPhyDe5aNakgtvP+0FIdciJUbYr34Uc0HMpLce4CpIDe/JMe/1H9qw8EDx/QR9hCwTH0HNehbvkDfYwQxLO3o9PQfIx96BoswrjcCmdi9PbxJmcxKY2JE1dkfZffL8mM/zVp/IBLyHfr7dHymebKu4jSfvrXYsQU18lUoXXjHUJ0jOr7+Jmb1nwq/EqWs
  template:
    metadata:
      name: telegram-bot-token
      namespace: monitoring
