apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    http:
      pprof:
        port: 6060
        enabled: false
      address: 0.0.0.0:3000
      session_ttl: 720h
    users:
      - name: oscar
        password: $2b$12$qn435P2flLPRj6qTaUbhoOFcnP0K1S3TFwYqWGZgf5msn/m4NMv8.
    auth_attempts: 5
    block_auth_min: 15
    theme: auto
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
      upstream_dns:
        - https://dns.cloudflare.com/dns-query
        - https://dns.google/dns-query
      bootstrap_dns:
        - 1.1.1.1
        - 8.8.8.8
      upstream_mode: load_balance
      enable_dnssec: true
      cache_size: 4194304
      cache_ttl_min: 0
      cache_ttl_max: 0
      cache_optimistic: true
      ratelimit: 0
      refuse_any: true
      serve_plain_dns: true
      trusted_proxies:
        - 127.0.0.0/8
        - ::1/128
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    filtering:
      protection_enabled: true
      filtering_enabled: true
      blocking_mode: default
      blocked_response_ttl: 10
      parental_enabled: false
      safebrowsing_enabled: false
      safe_search:
        enabled: false
      filters_update_interval: 24
      rewrites: []
    filters:
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
        name: AdGuard DNS filter
        id: 1
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
        name: AdAway Default Blocklist
        id: 2
    querylog:
      enabled: true
      file_enabled: true
      interval: 168h
      size_memory: 1000
      ignored: []
    statistics:
      enabled: true
      interval: 168h
      ignored: []
    log:
      enabled: true
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
      verbose: false
    schema_version: 29
