apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-arpa-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: home.arpa Root CA
  secretName: home-arpa-ca-secret
  duration: 87600h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 4096
  subject:
    organizations:
      - homelab
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: home-arpa-ca
spec:
  ca:
    secretName: home-arpa-ca-secret
