apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-adguard
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-cert-manager-issuers
    - name: infrastructure-longhorn
  interval: 10m0s
  path: ./clusters/homelab/infrastructure/adguard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
