apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sealed-secrets
    - name: infrastructure-cert-manager-issuers
    - name: infrastructure-longhorn
    - name: infrastructure-tailscale
  interval: 10m0s
  path: ./clusters/homelab/infrastructure/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
