---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCL/61QE5lbIfzGnGZhApFofAcRfGuYvH1qPz5bK+x9eej7uW4/4hv8jnTUGrigPMv9VqvkJmFvApsM17Js914wJH4hjTIrSbql2qQREg7mlpXH6S5u4Pc0LrYg+8hOPXXMbdVGLUXmNAAEXlUAbN3Ot+rvK9DSxtpy9TEinBeZfMt9kMWnDjTqEHgI55slws9BDHrZROilcPbzJDqKzibV7aLUVQwb33ueOjXJZ5BLX7iExEurBUX5nkC96klvSuMVhmu/vWaUURB1pcJYLWSgaM9UmHh7jq83rPzyVXQ96voK8AAqHeTiXMG9pNYPRGA2UDdmLIA0OSndb8yW4qemB9jlvT/fDubFh2OBiOHQlM+Pxwv4wu5ttm0J9XIW49W1I1HOf2+e3E9F0DCHqYRHLBk/wTg+rl79gtImeLl1Klzvsnl2RNLu0U+YgVZwnu93K7SdB5DofhXW1XUeFgqYK7g4ch7h86B1jv4v6GTUbHPh+thHEFN1UAEKeR+R1dCbq8eVnZRFF3JeD+p7Lf824Ok5IWNrk1HYxAXEo2EB+1VPozI87THPzhs2l5vwMzlZhb1FpwnUshBwgobtrBWZpZpFOBWREWEPuGgFq5SoPIsKXa3mncrxurj17NNYQvbW/XPFaMDIKC/JO9mI1xsi2+KlEiJR0GFxnjSWuWzM7stQ+CcYJSatRMta9p2iTUozJxY+pbLER3K46gVTNs+1G2/9wEdtzI78F8+el2EgOffBEgHBJojoffJYyheL
  template:
    metadata:
      name: telegram-token
      namespace: flux-system
