---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCQq/531X7hkRGK+46q4vvmqhJSNZfcEJ6DcIupOk/aGr79EkiAZ9XPr6Z0pGtJveKeX04Oos6s5qL2y5R8Ri4Rt6x2k/fHrlTcjFSMStGTxEFgT+Nwe5efuMxXA93OpzCp3LhsPs/LH/LbGGd60/b7jCb8O8BjxyUx7q0DJ51FAv5wMoOcN3RHhaF88i2XJUPG03xAqeLsTeEdD0V7g7sSn9Y8oKRIBqXAg0DIiqjhVn8AKSa+eFJt1a63+gRdBNpDfnWQLxaYdWoHIo8AUe3rzEwkzwgbB23AQ8g6tSw5sJWWzYsKm/ObYEhlgWEA+GeDrfiBvDxs8PBwBbkjA2+xt2Oha4TUebxM7zoZfeMDFvXbbbez2ZQIN9EsFS5Fvg8gmVvZtGz6MyAC3oUs13glhQYhfifF71Gd78j09qkw6BEmkn3fRUe/ZmIynOTJ/SlIxGVpMbNpEarXHLlKu1WEh5eaH4cyXaMFWJC+JigmQUlq9rp7PMeg9eD30lzlsCGLmuaQNVHmprN6Gf0Pk60dSHZBSnEs/Zq0T2ApnGWXC0YoDb4GWJzZlFcm/3NMHiSiJrjasl6GG2/pNUxF3i26uMn4Hdp82DcFzFsJPw1VLfL99lg4IOjdWplTlNxTaNQPp4NDzCwkIfWjOFJvdjBrQOaqkhLE//fu49QzXj39sfiyr5qrOdFJGzCAOeJjSQLkiWBpupBJE08SxLSRhZmDGg==
    client_secret: AgCb4HhLzV2sEenrkZMc36fu0jcJYTr1n91HZKzFmC9en7t8gHjiTQh+rDO/8TPfVL1a4EA3wNzqUA/3iSxyFeJ3eo32qrZ/UcdF5EAm5VG78zkb7Gx5oXsxQD4UbckKLES+Qv6PEeLgD3t+Dpk3L9sulB4a/Ah1CVVEWwgWnUs+idT6e2MIq73o0UDzLbFNgdExZXutaXZRY82Rw0WWNdPHoRqnGKXLjBt699vElHftFW6KlphtLpMcDJMdQ7tv3DxgbwJ0qgawse4expc4UVFlESs7ox6mcXIyPG6smuS2aqzoi3Y9OAit+VpGAdK8pHNZvWEpTTEQADsOZmmflJvFwuZ3LIB/7I83fH/dlpE+OwolhPahz0wtq/IOw1CLYqOfexvg9ZZFIeAQN810AK94fC3gDvRb31ojOq6mt4TOr7/LCL0ZCotW/eC2GtXKYN9cxiYxRMUCCg5ltDiRFtnE4nOp/dlFr5OjTeHcpEFcgPDytcC0W2PgLTNSkpGSNIJwgd+r7vRxfSrxlQYZSOFtYQM5L2RTN/MsanVb2OWGbOwquouv1OCP1m2AhhhpBo2mWkDLysZPZHdOTm++Oq0/YCXcmDqXrvL/SJayDmZ3+6ZPJVUhz8Na9FWmAWkNXClZhKQuRtCECQ+JxSKkE1D66x7SJfm+X9sqKs4oV/67lX62PYvDYBlacaEI8HOs1FHcEw5I1xvakt/HwsFaw5dRLulac6eDaP0mEWbZ7jT90me+lRzefILIjfghVIv3PQEQpfmvh06CLpvFPyI6WhPI
  template:
    metadata:
      name: tailscale-operator-oauth
      namespace: tailscale
